### ISSUE TITLE
Which ‘arch’ should I choose when training the language model

### ISSUE THREAD

**Issue by socaty** [teslacool/SCA#1]
Hi, tesla, 

When I use the code to train the language model follow your script，there was en error:
```
Traceback (most recent call last):
  File "train.py", line 431, in <module>
    main(args)
  File "train.py", line 77, in main
    if args.load_lm:
AttributeError: 'Namespace' object has no attribute 'load_lm'
```

Then I delete line 77-78，go on training,  still meet errors:
```
Traceback (most recent call last):
  File "train.py", line 431, in <module>
    main(args)
  File "train.py", line 42, in main
    model = task.build_model(args)
  File "/data/experiment/sca/fairseq/tasks/language_modeling.py", line 118, in build_model
    model = super().build_model(args)
  File "/data/experiment/sca/fairseq/tasks/fairseq_task.py", line 131, in build_model
    return models.build_model(args, self)
  File "/data/experiment/sca/fairseq/models/__init__.py", line 34, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/data/experiment/sca/fairseq/models/transformer.py", line 111, in build_model
    src_dict, tgt_dict = task.source_dictionary, task.target_dictionary
  File "/data/experiment/sca/fairseq/tasks/fairseq_task.py", line 201, in source_dictionary
    raise NotImplementedError
NotImplementedError
```

Following is my script:
```
num=0
data_bin=/data/experiment/sca/data/lmofch
save_dir=model-ch
dropout=0.1
arch=transformer
max_tokens=4096
criterion=label_smoothed_cross_entropy
label_smoothing=0.1
lrscheduler=inverse_sqrt

CUDA_VISIBLE_DEVICES=$num python train.py $data_bin \
                        --task language_modeling \
                        --arch $arch \
                        --optimizer adam \
                        --adam-betas '(0.9, 0.98)' \
                        --clip-norm 0.0 \
                        --lr-scheduler $lrscheduler \
                        --warmup-init-lr 1e-07 \
                        --warmup-updates 4000 \
                        --lr 0.0005 \
                        --min-lr 1e-09 \
                        --dropout $dropout \
                        --weight-decay 0.0 \
                        --criterion $criterion \
                        --label-smoothing $label_smoothing \
                        --max-tokens $max_tokens \
                        --tokens-per-sample 4096 \
                        --save-dir $save_dir \
                        --update-freq 16
```

So I wonder if it is I choose the wrong arch that bring about the error.

**Comment by teslacool** [comment]
As you can see at [line](https://github.com/teslacool/SCA/blob/b48b0af5b19df7577c1134629b29e29be0d2e28c/fairseq/models/transformer.py#L1543), the arch _transformer_  you used is an arch for NMT rather than for  language modeling task.

You should specify an arch registered for model _transformer_lm_ , such as transformer_lm or define by yourself. Our language modeling config has been described in our paper.

Besides, I suggest you train your language model with base fairseq repos, as I have modified collate_tokens function. I do not know whether there is a bad influence.

**Comment by socaty** [comment]
OK， thanks a lot!
