### ISSUE TITLE
not able to train a LM with SCA

### ISSUE THREAD

**Issue by nicolabertoldi** [teslacool/SCA#11]
I am trying to use your script ``./train.py`` (instead of the official fairseq-train) to train the language models.

I run such a command
 ```python3 ../../../code/SCA/train.py --task language_modeling data-bin/wikitext-103_SMALL/ --save-dir checkpoints_SCA/transformer_wikitext-103i_SMALL --arch transformer_lm_wiki103   --max-update 286000 --max-lr 1.0 --t-mult 2 --lr-period-updates 270000 --lr-scheduler cosine --lr-shrink 0.75   --warmup-updates 16000 --warmup-init-lr 1e-07 --min-lr 1e-09 --optimizer nag --lr 0.0001 --clip-norm 0.1   --criterion adaptive_loss --max-tokens 2048 --update-freq 2 --tokens-per-sample 3072 --seed 1   --sample-break-mode none --skip-invalid-size-inputs-valid-test --ddp-backend no_c10d --sample-break-mode eos --no-progress-bar --log-interval 100  --no-epoch-checkpoints --save-interval-updates 1000 --keep-interval-updates 10 --max-update 200000
```

and I got this error
```
Traceback (most recent call last):
  File "../../../code/SCA//train.py", line 437, in <module>
    main(args)
  File "../../../code/SCA//train.py", line 89, in main
    trainer.dummy_train_step([dummy_batch])
  File "/home/nicola/workspace/SCA/code/SCA/fairseq/trainer.py", line 335, in dummy_train_step
    self.train_step(dummy_batch, dummy_batch=True)
  File "/home/nicola/workspace/SCA/code/SCA/fairseq/trainer.py", line 188, in train_step
    ignore_grad
  File "/home/nicola/workspace/SCA/code/SCA/fairseq/tasks/fairseq_task.py", line 169, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nicola/workspace/SCA/code/SCA/fairseq/criterions/adaptive_loss.py", line 41, in forward
    assert hasattr(model.decoder, 'adaptive_softmax') and model.decoder.adaptive_softmax is not None
AssertionError

```

Note that the same parameters work well when I use ``fairseq-train``
The data bin were generated with ``fairseq-preprocess`` following your documentation.

**Comment by teslacool** [comment]
From this error

`assert hasattr(model.decoder, 'adaptive_softmax') and model.decoder.adaptive_softmax is not None`

I think this was because you use `adaptive_loss` as your criterions, but you did not specify your `adaptive_softmax_cutoff` arguments.
